shell:completion subshell
feature:install jpa
feature:install jndi
feature:install transaction
feature:install jdbc
feature:install openjpa
bundle:install -s mvn:com.github.funthomas424242/saghallo-command/1.0.2-SNAPSHOT
bundle:install -s mvn:com.h2database/h2/1.3.172
jdbc:ds-create -dbName H2 -url jdbc:h2:${karaf.data}/database/h2Test -u sa -dn org.h2.jdbcx.JdbcDataSource jdbc/datenquelle
bundle:install -s mvn:com.github.funthomas424242/inventory-command/1.0.2-SNAPSHOT

